version: '3'
services:
  webapp:
    build: .
    image: yang3498/web_docker-webapp:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=hospital_managerment
      - MYSQL_USER=root
      - MYSQL_PASSWORD=20050303YMZ
  db:
    image: yang3498/web_docker-db-with-data:latest
    environment:
      MYSQL_ROOT_PASSWORD: 20050303YMZ
      MYSQL_DATABASE: hospital_managerment
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
